{{- if and (and .Values.livekit.turn.enabled .Values.livekit.turn.tls_port) .Values.turnLoadbalancer.enable }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "livekit-server.fullname" . }}-turn'
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  {{- with .Values.livekit.turn.loadBalancerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ default "LoadBalancer" .Values.livekit.turn.serviceType }}
  {{- if .Values.livekit.turn.loadBalancerIP }}
  loadBalancerIP: {{ .Values.livekit.turn.loadBalancerIP }}
  {{- end }}
  {{- if eq (default "LoadBalancer" .Values.livekit.turn.serviceType) "NodePort" }}
  externalTrafficPolicy: {{ default "Local" .Values.livekit.turn.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 443
      targetPort: {{ .Values.livekit.turn.tls_port }}
      protocol: TCP
      {{- if and (eq (default "LoadBalancer" .Values.livekit.turn.serviceType) "NodePort") .Values.livekit.turn.nodePort }}
      nodePort: {{ .Values.livekit.turn.nodePort }}
      {{- end }}
  selector:
    {{- include "livekit-server.selectorLabels" . | nindent 4 }}
{{- end }}
